version: '3.7'
services:
    db:
        image: postgres:13.4
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        hostname: postgres
        user: root

    java:
        build: .
        ports: 
            - 8000:8000
        tty: true
        volumes: 
            - ${SRC_PATH}:/root/src
        depends_on: 
            - db

volumes:
    postgres_volume:
        external: true