version: '3.7'
services:
    db:
        image: postgres:13.4
        container_name: sb_db
        # ports:
            # - 5432:5432
        volumes:
            - postgres_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: password
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        restart: always

    java:
        build: .
        # image: amazonlinux:latest
        container_name: sb_app
        ports: 
            - 8080:8080
        tty: true
        privileged: true               
        depends_on: 
            - db
        restart: always           

volumes:
    postgres_volume:
        external: true