version: '3.7'
services:    
    db:
        image: postgres:13.4
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"       
    web:
        build: .        
        container_name: CheckTrend_Python3
        tty: true
        ports: 
            - 8000:8000
        depends_on: 
            - db
        