version: '3.7'
services:    
    app:
        build: .        
        container_name: react
        tty: true
        hostname: react         
        ports: 
            - 3000:3000
            - 80:80
        privileged: true
        command: /sbin/init
        