version: '3.7'
services:    
    app:
        build: .        
        container_name: react
        volumes:
            - react_app_volume:/root/src
        tty: true
        hostname: react         
        ports: 
            - 3000:3000
            - 80:80
        restart: always
        privileged: true
        command: /sbin/init

volumes: 
    react_app_volume:
        external: true