version: '3.7'
services:    
    react:
        build: .        
        container_name: react
        volumes:
            - ${SRC_PATH}:/root/src
        tty: true
        hostname: react         
        ports: 
            - 3000:3000
        restart: always
