FROM ubuntu:latest
USER root

ENV TZ JST-9
ENV TERM xterm

RUN apt upgrade -y
RUN apt update -y

RUN apt install tzdata -y
RUN apt install nodejs npm -y
RUN apt install vim wget tar git apache2 -y

# RUN npm install -g npm-check-updates
RUN npm update

CMD ["apachectl", "-D", "FOREGROUND"]