FROM ubuntu:latest
USER root

ENV TZ JST-9
ENV TERM xterm

RUN apt upgrade -y
RUN apt update -y

RUN apt install tzdata -y
RUN apt install vim wget tar git apache2 -y

RUN mkdir /usr/local/src/download
RUN cd /usr/local/src/download

# # Download .NET6 SDK
RUN wget https://download.visualstudio.microsoft.com/download/pr/17b6759f-1af0-41bc-ab12-209ba0377779/e8d02195dbf1434b940e0f05ae086453/dotnet-sdk-6.0.100-linux-x64.tar.gz

RUN mkdir /opt/dotnet
RUN tar zxvf dotnet-sdk-6.0.100-linux-x64.tar.gz -C /opt/dotnet

# # add dotnet command path
RUN echo "#!/bin/sh" > ~/.bashrc
RUN echo "export DOTNET_ROOT=/opt/dotnet" >> ~/.bashrc
RUN echo "export PATH=\$DOTNET_ROOT:\$PATH" >> ~/.bashrc
RUN echo "export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1" >> ~/.bashrc
RUN echo "export ASPNETCORE_ENVIRONMENT=Development" >> ~/.bashrc
RUN echo "# Add .NET Core SDK tools" >> ~/.bashrc
RUN echo "export PATH=\$PATH:/root/.dotnet/tools" >> ~/.bashrc

# # update dotnet ef commamd
RUN /opt/dotnet/dotnet tool update --global dotnet-ef

CMD ["apachectl", "-D", "FOREGROUND"]