version: '3.7'
services:
    db:
        image: postgres:latest
        container_name: sample_db
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: dev_asp
            POSTGRES_PASSWORD: password
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8"

    backend:
        build:
            context: ./context
            dockerfile: Dockerfile_dotnet6
        container_name: backend-app
        ports:
            - 3001:3000
        tty: true
        depends_on:
            - db
    frontend:
        build:
            context: ./context
            dockerfile: Dockerfile_nodejs
        container_name: front-app
        ports: 
            - 80:80  
        tty: true
        depends_on: 
            - db
