version: '3.7'
services:    
    db:
        image: postgres:13.4
        container_name: postgres
        ports:
            - 5432:5432
        # volumes:
        #     - postgres_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"        
        restart: always

    web:
        build: .        
        container_name: drf
        volumes:
            - ${SRC_PATH}:/root/src
        tty: true
        hostname: drf
        restart: always        
        ports: 
            - 8000:8000
        depends_on: 
            - db

    pgadmin4:
        image: dpage/pgadmin4:5.6
        container_name: pgadmin4
        ports:
            - 81:80
        environment:
            PGADMIN_DEFAULT_EMAIL: root@example.com
            PGADMIN_DEFAULT_PASSWORD: root
        hostname: pgadmin4
        depends_on:
            - db
        restart: always        

# volumes:
#     postgres_volume:
#         external: true
#     pgadmin4_volume:
#         external: true