version: '3.7'
services:    
    db:
        image: postgres:13.4
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - postgres_data_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"        
        restart: always

    rest_api:
        build:
            context: .
            dockerfile: DockerfilePython
        container_name: drf
        volumes:
            - drf_data_volume:/root/src
        tty: true
        hostname: drf
        restart: always        
        ports: 
            - 8000:8000
        depends_on: 
            - db
        restart: always  

    web_front:
        build:
            context: .
            dockerfile: DockerfileNode
        container_name: react
        volumes:
            - react_data_volume:/root/src
        tty: true  
        ports: 
            - 3000:3000
        restart: always
        depends_on: 
            - db

volumes: 
    postgres_data_volume:
    drf_data_volume:
    react_data_volume:
    